services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fiddle
      POSTGRES_PASSWORD: fiddle
      POSTGRES_DB: fiddle
    volumes:
      - ./data/psql:/var/lib/postgresql/data
