services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: cadence
      POSTGRES_PASSWORD: cadence
      POSTGRES_DB: cadence
    volumes:
      - ./data/psql:/var/lib/postgresql/data
